# Generated by Django 3.2.16 on 2023-11-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0002_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height_before',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width_before',
        ),
    ]
