# Generated by Django 3.2.16 on 2023-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0003_auto_20231129_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='height_after',
            new_name='image_height',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='width_after',
            new_name='image_width',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
