# Generated by Django 3.2.16 on 2023-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0004_auto_20231129_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
