# Generated by Django 3.2.16 on 2023-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0009_alter_image_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='')),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='UnprocessedImage',
        ),
    ]
