# Generated by Django 3.2.16 on 2023-12-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0010_auto_20231201_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedimage',
            old_name='uid',
            new_name='task_id',
        ),
    ]
