# Generated by Django 3.2.16 on 2023-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0011_rename_uid_processedimage_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='task_id',
            field=models.TextField(),
        ),
    ]
